apiVersion: v1
kind: Service
metadata:
  name: swift-rest-app-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: swift-rest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000